osx_image: xcode9
language: objective-c       
xcode_project: Demo/KafkaExample.xcworkspace
xcode_scheme: KafkaExample

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version

